[workspace]
members = ["music-app-frontend","music-app-backend","music-app-lib"]
resolver = "2"

[workspace.package]
authors = ["Grant Duchars"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
