[workspace]
members = ["music-app-ui","music-app-backend","music-app-lib"]
authors = ["Grant Duchars"]
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace.package]
authors = ["Grant Duchars"]
version = "0.1.0"
edition = "2021"